// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyllabusAI.Data;

#nullable disable

namespace SyllabusAI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410083221_addFeedbackQuestionsAndAnswers")]
    partial class addFeedbackQuestionsAndAnswers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SyllabusAI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FeedbackClosesAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FeedbackOpensAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighlightKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SyllabusContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("CourseCode", "InstructorId")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SyllabusAI.Models.CourseFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("CourseId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("CourseFeedbacks");
                });

            modelBuilder.Entity("SyllabusAI.Models.CourseFeedbackAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseFeedbackId")
                        .HasColumnType("int");

                    b.Property<int>("FeedbackQuestionId")
                        .HasColumnType("int");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackQuestionId");

                    b.HasIndex("CourseFeedbackId", "FeedbackQuestionId")
                        .IsUnique();

                    b.ToTable("CourseFeedbackAnswers");
                });

            modelBuilder.Entity("SyllabusAI.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SyllabusAI.Models.FeedbackQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionNo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionNo")
                        .IsUnique();

                    b.ToTable("FeedbackQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            QuestionNo = 1,
                            Text = "Dersin hedefleri ve icerigi donem basinda acik sekilde paylasildi."
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            QuestionNo = 2,
                            Text = "Ders plani (syllabus) ile islenen konular su ana kadar uyumluydu."
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            QuestionNo = 3,
                            Text = "Kullanilan dijital platformlar ders takibi ve etkilesim icin yeterliydi."
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            QuestionNo = 4,
                            Text = "Sunulan ders materyalleri (notlar, sunumlar vb.) yeterli ve faydaliydi."
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            QuestionNo = 5,
                            Text = "Ders kapsaminda onerilen ek kaynaklara ve okumalara erisim kolaydi."
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            QuestionNo = 6,
                            Text = "Islenen ders konularini su ana kadar teorik duzeyde iyi anlayabildim."
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            QuestionNo = 7,
                            Text = "Konularin pekismesi icin sinifta daha fazla tekrar veya uygulama yapilmasi gerektigini dusunuyorum."
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            QuestionNo = 8,
                            Text = "Dersin islenisi sirasinda farkli ogrenme hizlarina ve seviyelerine sahip ogrenciler gozetildi."
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            QuestionNo = 9,
                            Text = "Ders kapsaminda yapilan ornekler ve uygulamalar, gercek hayattaki/mesleki senaryolarla iyi iliskilendirildi."
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            QuestionNo = 10,
                            Text = "Dersin islenis temposu (ilerleyis hizi), konulari sindirmem ve not almam icin uygundur."
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            QuestionNo = 11,
                            Text = "Anlatilan konularin zorluk seviyesi, sahip oldugum on bilgilerle ve yetkinligimle ortusmektedir."
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            QuestionNo = 12,
                            Text = "Ders sirasinda soru sorma, tartismaya katilma ve fikir beyan etme konusunda kendimi tesvik edilmis hissediyorum."
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            QuestionNo = 13,
                            Text = "Verilen odevler, projeler veya kisa sinavlar ogrenme surecime gercek anlamda katki saglamaktadir."
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            QuestionNo = 14,
                            Text = "Dersin icerigi ve hocanin anlatim tarzi, konuya olan merakimi ve derse olan motivasyonumu canli tutmaktadir."
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            QuestionNo = 15,
                            Text = "Egitmen, karmasik kavramlari aciklarken farkli yontemler (gorsel araclar, benzetmeler, vaka analizleri vb.) kullanarak anlasilirligi artirmaktadir."
                        });
                });

            modelBuilder.Entity("SyllabusAI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Student"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instructor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("SyllabusAI.Models.SyllabusChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "ChunkIndex");

                    b.ToTable("SyllabusChunks");
                });

            modelBuilder.Entity("SyllabusAI.Models.SyllabusPdfUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredRelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("SyllabusPdfUploads");
                });

            modelBuilder.Entity("SyllabusAI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SyllabusAI.Models.Course", b =>
                {
                    b.HasOne("SyllabusAI.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SyllabusAI.Models.CourseFeedback", b =>
                {
                    b.HasOne("SyllabusAI.Models.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyllabusAI.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SyllabusAI.Models.CourseFeedbackAnswer", b =>
                {
                    b.HasOne("SyllabusAI.Models.CourseFeedback", "CourseFeedback")
                        .WithMany("Answers")
                        .HasForeignKey("CourseFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyllabusAI.Models.FeedbackQuestion", "FeedbackQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("FeedbackQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseFeedback");

                    b.Navigation("FeedbackQuestion");
                });

            modelBuilder.Entity("SyllabusAI.Models.Enrollment", b =>
                {
                    b.HasOne("SyllabusAI.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyllabusAI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyllabusAI.Models.SyllabusChunk", b =>
                {
                    b.HasOne("SyllabusAI.Models.Course", "Course")
                        .WithMany("SyllabusChunks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SyllabusAI.Models.SyllabusPdfUpload", b =>
                {
                    b.HasOne("SyllabusAI.Models.Course", "Course")
                        .WithMany("SyllabusPdfUploads")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SyllabusAI.Models.User", b =>
                {
                    b.HasOne("SyllabusAI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SyllabusAI.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("SyllabusChunks");

                    b.Navigation("SyllabusPdfUploads");
                });

            modelBuilder.Entity("SyllabusAI.Models.CourseFeedback", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SyllabusAI.Models.FeedbackQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SyllabusAI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
